name=input("hola, cual es tu nombre? ")
age=input("cual es tu edad? ")
address=input("donde vives?")
job=input("cual quieres que sea tu trabajo?")
print("\n\nhola %s, tienes %s años y vives en %s, por lo que calificas para el empleo de %s " % (name,age,address,job)) 
